const memberDetails = {
  refname: "ANUP S R",
  rankDesignation: "Developer",
  serviceId: "DHS-4056",
  relationship: "Friend",
  saluation: "Mr",
  propertyDetails: {
    projectName: "defence habitat - tapasihalli",
    propertySize: 1200,
    pricePerSqft: 1099,
    propertyCost: 1318800,
    percentage: 25,
    percentageCost: 329700,
  },
  name: "Test Name",
  mobileNumber: 9886202952,
  AlternativeNumber: 0,
  email: "enquiry@rajavrukshagroup.in",
  dateofbirth: "09-05-2025",
  fatherName: "Mohammed",
  contactAddress: "Davanagere",
  permanentAddress: "Bangalore",
  workingAddress: "Muneshwara Nagar, Bengaluru",
  MemberPhoto:
    "https://res.cloudinary.com/dwmeclnky/image/upload/v1746771614/dhs-project-status/member-uploads/duyqlyw80l8guv889dwc.jpg",
  MemberSign:
    "https://res.cloudinary.com/dwmeclnky/image/upload/v1746771615/dhs-project-status/member-uploads/z1tkiu5zye6hp0rh1bh4.jpg",
  nomineeName: "Dodda Ganesh",
  nomineeAge: 55,
  nomineeRelation: "Father",
  nomineeAddress: "#94,Gowdru Mane",
  SeniorityID: "DHS-3000",
  MembershipNo: "1",
  ConfirmationLetterNo: "1",
  ShareCertificateNumber: "-1",
  ReceiptNo: "1",
  date: "09-05-2025",
  NoofShares: 1,
  ShareFee: 2000,
  MembershipFee: 2500,
  ApplicationFee: 1999,
  AdmissionFee: 250,
  MiscellaneousExpenses: 250,
  PaymentType: "Membership fee",
  PaymentMode: "cash",
  BankName: "Union Bank Of India",
  BranchName: "Hebbal",
  Amount: 4999,
};

export default memberDetails;
