// const memberDetails = {
//   refname: "ANUP S R",
//   rankDesignation: "Developer",
//   serviceId: "DHS-4056",
//   relationship: "Friend",
//   saluation: "Mr",
//   propertyDetails: {
//     projectName: "defence habitat - tapasihalli",
//     propertySize: 1200,
//     pricePerSqft: 1099,
//     propertyCost: 1318800,
//     percentage: 25,
//     percentageCost: 329700,
//   },
//   name: "Test Name",
//   mobileNumber: 9886202952,
//   AlternativeNumber: 0,
//   email: "enquiry@rajavrukshagroup.in",
//   dateofbirth: "09-05-2025",
//   fatherName: "Mohammed",
//   contactAddress: "Davanagere",
//   permanentAddress: "Bangalore",
//   workingAddress: "Muneshwara Nagar, Bengaluru",
//   MemberPhoto:
//     "https://res.cloudinary.com/dwmeclnky/image/upload/v1746771614/dhs-project-status/member-uploads/duyqlyw80l8guv889dwc.jpg",
//   MemberSign:
//     "https://res.cloudinary.com/dwmeclnky/image/upload/v1746771615/dhs-project-status/member-uploads/z1tkiu5zye6hp0rh1bh4.jpg",
//   nomineeName: "Dodda Ganesh",
//   nomineeAge: 55,
//   nomineeRelation: "Father",
//   nomineeAddress: "#94,Gowdru Mane",
//   SeniorityID: "DHS-3000",
//   MembershipNo: "1",
//   ConfirmationLetterNo: "1",
//   ShareCertificateNumber: "-1",
//   ReceiptNo: "1",
//   date: "09-05-2025",
//   NoofShares: 1,
//   ShareFee: 2000,
//   MembershipFee: 2500,
//   ApplicationFee: 1999,
//   AdmissionFee: 250,
//   MiscellaneousExpenses: 250,
//   PaymentType: "Membership fee",
//   PaymentMode: "cash",
//   BankName: "Union Bank Of India",
//   BranchName: "Hebbal",
//   Amount: 4999,
// };

const memberDetails = [
  {
    refname: "Shridhar",
    rankDesignation: "Developer",
    serviceId: "DHS-4058",
    relationship: "Friend",
    saluation: "Mr",
    propertyDetails: {
      projectName: "defence habitat - marasandra",
      propertySize: 1500,
      pricePerSqft: 1399,
      propertyCost: 2098500,
      percentage: 30,
      percentageCost: 629550,
    },
    name: "Shanmukha",
    mobileNumber: 9886202952,
    AlternativeNumber: 0,
    email: "sranup007@gmail.com",
    dateofbirth: "11-05-2025",
    fatherName: "Muhammaed",
    contactAddress: "Mariyappanapalya Main Road,Bangalore",
    permanentAddress: "14th Cross, Ullal Main Road,",
    workingAddress: "Muneshwara Nagar, Bengaluru",
    MemberPhoto:
      "https://res.cloudinary.com/dwmeclnky/image/upload/v1746870656/dhs-project-status/member-uploads/h6im3yr1cfxh3zzd1zc7.jpg",
    MemberSign:
      "https://res.cloudinary.com/dwmeclnky/image/upload/v1746870660/dhs-project-status/member-uploads/e7yequoltoynurdwjp4y.jpg",
    nomineeName: "Begam",
    nomineeAge: 55,
    nomineeRelation: "Mother",
    nomineeAddress: "#94,Gowdru Mane",
    SeniorityID: "DHS-700",
    MembershipNo: "1007",
    ConfirmationLetterNo: "1007",
    ShareCertificateNumber: "10007",
    ReceiptNo: "1237",
    date: "12-05-2025",
    NoofShares: 2,
    ShareFee: 2500,
    MembershipFee: 2500,
    ApplicationFee: 250,
    AdmissionFee: 250,
    MiscellaneousExpenses: 500,
    PaymentType: "Membership fee",
    PaymentMode: "cash",
    BankName: "Union Bank Of India",
    BranchName: "Hebbal",
    Amount: 2500,
  },
  {
    refname: "Damodar",
    rankDesignation: "Developer",
    serviceId: "DHS-4058",
    relationship: "Friend",
    saluation: "Mr",
    propertyDetails: {
      projectName: "defence habitat - marasandra",
      propertySize: 1500,
      pricePerSqft: 1399,
      propertyCost: 2098500,
      percentage: 30,
      percentageCost: 629550,
    },
    name: "Shanmukha Shivanda",
    mobileNumber: 9886202952,
    AlternativeNumber: 0,
    email: "sranup007@gmail.com",
    dateofbirth: "11-05-2025",
    fatherName: "Muhammaed",
    contactAddress: "Mariyappanapalya Main Road,Bangalore",
    permanentAddress: "14th Cross, Ullal Main Road,",
    workingAddress: "Muneshwara Nagar, Bengaluru",
    MemberPhoto:
      "https://res.cloudinary.com/dwmeclnky/image/upload/v1746870656/dhs-project-status/member-uploads/h6im3yr1cfxh3zzd1zc7.jpg",
    MemberSign:
      "https://res.cloudinary.com/dwmeclnky/image/upload/v1746870660/dhs-project-status/member-uploads/e7yequoltoynurdwjp4y.jpg",
    nomineeName: "Begam",
    nomineeAge: 55,
    nomineeRelation: "Mother",
    nomineeAddress: "#94,Gowdru Mane",
    SeniorityID: "DHS-800",
    MembershipNo: "1008",
    ConfirmationLetterNo: "1008",
    ShareCertificateNumber: "10008",
    ReceiptNo: "1238",
    date: "12-05-2000",
    NoofShares: 2,
    ShareFee: 2500,
    MembershipFee: 2500,
    ApplicationFee: 250,
    AdmissionFee: 250,
    MiscellaneousExpenses: 500,
    PaymentType: "Membership fee",
    PaymentMode: "cash",
    BankName: "Union Bank Of India",
    BranchName: "Hebbal",
    Amount: 2500,
  },
  {
    refname: "Shambhu",
    rankDesignation: "Developer",
    serviceId: "DHS-4058",
    relationship: "Friend",
    saluation: "Mr",
    propertyDetails: {
      projectName: "defence habitat - marasandra",
      propertySize: 1500,
      pricePerSqft: 1399,
      propertyCost: 2098500,
      percentage: 30,
      percentageCost: 629550,
    },
    name: "Iqbal",
    mobileNumber: 9886202952,
    AlternativeNumber: 0,
    email: "sranup007@gmail.com",
    dateofbirth: "11-05-2025",
    fatherName: "Muhammaed",
    contactAddress: "Mariyappanapalya Main Road,Bangalore",
    permanentAddress: "14th Cross, Ullal Main Road,",
    workingAddress: "Muneshwara Nagar, Bengaluru",
    MemberPhoto:
      "https://res.cloudinary.com/dwmeclnky/image/upload/v1746870656/dhs-project-status/member-uploads/h6im3yr1cfxh3zzd1zc7.jpg",
    MemberSign:
      "https://res.cloudinary.com/dwmeclnky/image/upload/v1746870660/dhs-project-status/member-uploads/e7yequoltoynurdwjp4y.jpg",
    nomineeName: "Begam",
    nomineeAge: 55,
    nomineeRelation: "Mother",
    nomineeAddress: "#94,Gowdru Mane",
    SeniorityID: "DHS-900",
    MembershipNo: "1009",
    ConfirmationLetterNo: "1009",
    ShareCertificateNumber: "10009",
    ReceiptNo: "1239",
    date: "01-05-2025",
    NoofShares: 2,
    ShareFee: 2500,
    MembershipFee: 2500,
    ApplicationFee: 250,
    AdmissionFee: 250,
    MiscellaneousExpenses: 500,
    PaymentType: "Membership fee",
    PaymentMode: "cash",
    BankName: "Union Bank Of India",
    BranchName: "Hebbal",
    Amount: 2500,
  },
  {
    refname: "Shambhu",
    rankDesignation: "Developer",
    serviceId: "DHS-4058",
    relationship: "Friend",
    saluation: "Mr",
    propertyDetails: {
      projectName: "defence habitat - marasandra",
      propertySize: 1500,
      pricePerSqft: 1399,
      propertyCost: 2098500,
      percentage: 30,
      percentageCost: 629550,
    },
    name: "Suresh",
    mobileNumber: 9886202952,
    AlternativeNumber: 0,
    email: "sranup007@gmail.com",
    dateofbirth: "11-05-2025",
    fatherName: "Muhammaed",
    contactAddress: "Mariyappanapalya Main Road,Bangalore",
    permanentAddress: "14th Cross, Ullal Main Road,",
    workingAddress: "Muneshwara Nagar, Bengaluru",
    MemberPhoto:
      "https://res.cloudinary.com/dwmeclnky/image/upload/v1746870656/dhs-project-status/member-uploads/h6im3yr1cfxh3zzd1zc7.jpg",
    MemberSign:
      "https://res.cloudinary.com/dwmeclnky/image/upload/v1746870660/dhs-project-status/member-uploads/e7yequoltoynurdwjp4y.jpg",
    nomineeName: "Begam",
    nomineeAge: 55,
    nomineeRelation: "Mother",
    nomineeAddress: "#94,Gowdru Mane",
    SeniorityID: "DHS-450",
    MembershipNo: "450",
    ConfirmationLetterNo: "450",
    ShareCertificateNumber: "450",
    ReceiptNo: "450",
    date: "04-05-2025",
    NoofShares: 2,
    ShareFee: 2500,
    MembershipFee: 2500,
    ApplicationFee: 250,
    AdmissionFee: 250,
    MiscellaneousExpenses: 500,
    PaymentType: "Membership fee",
    PaymentMode: "cash",
    BankName: "Union Bank Of India",
    BranchName: "Hebbal",
    Amount: 2500,
  },
  {
    refname: "Girish",
    rankDesignation: "Developer",
    serviceId: "DHS-4058",
    relationship: "Friend",
    saluation: "Mr",
    propertyDetails: {
      projectName: "defence habitat - marasandra",
      propertySize: 1500,
      pricePerSqft: 1399,
      propertyCost: 2098500,
      percentage: 30,
      percentageCost: 629550,
    },
    name: "Giridhar",
    mobileNumber: 9886202952,
    AlternativeNumber: 0,
    email: "sranup007@gmail.com",
    dateofbirth: "11-05-2025",
    fatherName: "Muhammaed",
    contactAddress: "Mariyappanapalya Main Road,Bangalore",
    permanentAddress: "14th Cross, Ullal Main Road,",
    workingAddress: "Muneshwara Nagar, Bengaluru",
    MemberPhoto:
      "https://res.cloudinary.com/dwmeclnky/image/upload/v1746870656/dhs-project-status/member-uploads/h6im3yr1cfxh3zzd1zc7.jpg",
    MemberSign:
      "https://res.cloudinary.com/dwmeclnky/image/upload/v1746870660/dhs-project-status/member-uploads/e7yequoltoynurdwjp4y.jpg",
    nomineeName: "Begam",
    nomineeAge: 55,
    nomineeRelation: "Mother",
    nomineeAddress: "#94,Gowdru Mane",
    SeniorityID: "DHS-4500",
    MembershipNo: "4500",
    ConfirmationLetterNo: "4500",
    ShareCertificateNumber: "4500",
    ReceiptNo: "4500",
    date: "04-05-1990",
    NoofShares: 2,
    ShareFee: 2500,
    MembershipFee: 2500,
    ApplicationFee: 250,
    AdmissionFee: 250,
    MiscellaneousExpenses: 500,
    PaymentType: "Membership fee",
    PaymentMode: "cash",
    BankName: "Union Bank Of India",
    BranchName: "Hebbal",
    Amount: 2500,
  },
];

export default memberDetails;
